name: Fetch Gold Price

on:
  schedule:
    - cron: '* * * * *' # Runs approximately every minute
  workflow_dispatch: # Allows manual trigger

jobs:
  fetch-price:
    runs-on: ubuntu-latest
    permissions:
      contents: write # <--- ADD THIS LINE (or ensure it's set)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch and save gold price
        run: python fetch_price.py

      - name: Commit and push if changes
        run: |
          cd ${{ github.workspace }}
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/gold-price.json
          git commit -m "Update gold price" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
